/* This file is automatically generated by the DailyBuild script. */
#if 0
// just a dummy section to make the file more like the generated one from the build maching
// note:  if the format of this file changes dramatically, you will have to change 
// CSharpVersionWriter in BuildTools, as we use it to generate src\include\dotNet\AssemblyVersion.cs
// for C# projects
#else // MAX
  #define VERSION_STRING  "Neptune with PDBs N845_RL_x64 02-27-2018 18:58 6b4316d87cb8d4a016c88fdf479827a1f3279f79"
  #define VERSION_INT   845
#endif

